spring:
  datasource:
    url: ${LOS_DATABASE_URL}
    username: ${LOS_DATABASE_USERNAME}
    password: ${LOS_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate